# Application specific like croco related


[__many__]

    [[content]]
    commandline=string(default=None)
    run_dir=string(default="{{ scratch_dir }}/woom/{{ task_path }}")
    env=string(default=None)  # env name declared in host.cfg
    template=string(default=job.sh)

    [[artifacts]]
        [[[__many__]]]
            path=pass # file or jinja filter name
            check=boolean(default=True)
            callable=boolean(default=False) # if true, paths value is paths generator function

            [[[[kwargs]]]] # extra parameters when using a callable
            __many__=string

    [[fill]]
        [[[__many__]]]
        template=string
        destination=string

    [[submit]]
    queue=string(default=None) # generic submission queue name (see hosts.cfg)
    nnodes=integer(default=None) # number of nodes
    ncpus=integer(default=None) # number of cpus per task
    ngpus=integer(default=None) # number of gpus per task
    memory=string(default=None) # max memory
    pmem=string(default=None) # max memory per process
    time=string(default=None) # max user time
    #log_out=string(default=None)
    mail=string(default=None) # email for reports
    blocking=boolean(default=True) # it must finish before dependencies start
    extra=string(default="-koed") # extra raw qsub flags (passed verbatim)
    __many__=string # additional raw qsub flags, passed verbatim (e.g. myopt = "-l place=scatter")
