name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
          **/pyproject.toml
          **/setup.py
          **/setup.cfg
    
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y fonts-cantarell
    
    - name: Install Python dependencies
      run: |
        pip install -U pip
        pip install -e .[docs]
    
    - name: Build documentation
      run: |
        cd docs
        make html
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html
        #retention-days: 7

  deploy_pages:
    runs-on: ubuntu-latest
    needs: build_documentation
    if: github.ref == 'refs/heads/develop'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Download documentation artifacts
      uses: actions/download-artifact@v5
      with:
        name: documentation
        path: ./public
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4